# [target.riscv32imc-unknown-none-elf]
# runner = "espflash flash --monitor"
# rustflags = [
#     "-C", "link-arg=-Tlinkall.x",
#     "-C", "link-arg=-Trom_functions.x",

#     "-C", "force-frame-pointers",

#     # Enable the atomic codegen option for RISCV
#     "-C", "target-feature=+a",

#     # tell the core library have atomics even though it's not specified in the target definition
#     "--cfg", "target_has_atomic_load_store",
#     "--cfg", 'target_has_atomic_load_store="8"',
#     "--cfg", 'target_has_atomic_load_store="16"',
#     "--cfg", 'target_has_atomic_load_store="32"',
#     "--cfg", 'target_has_atomic_load_store="ptr"',
#     # enable cas
#     "--cfg", "target_has_atomic",
#     "--cfg", 'target_has_atomic="8"',
#     "--cfg", 'target_has_atomic="16"',
#     "--cfg", 'target_has_atomic="32"',
#     "--cfg", 'target_has_atomic="ptr"',
# ]

# [target.riscv32imac-unknown-none-elf]
# runner = "espflash flash --monitor"
# rustflags = [
#     "-C", "link-arg=-Tlinkall.x",
#     "-C", "link-arg=-Trom_functions.x",
#     "-C", "force-frame-pointers",
# ]

# [target.xtensa-esp32-none-elf]
# runner = "espflash flash --monitor"
# rustflags = [
#     # "-C", "link-arg=-Tlinkall.x",
#     # "-C", "link-arg=-nostartfiles",
#     # "-C", "force-frame-pointers",
#     # "-C", "target-feature=+s32c1i",
#     # "--cfg", "target_has_atomic_load_store",
#     # "--cfg", 'target_has_atomic_load_store="8"',
#     # "--cfg", 'target_has_atomic_load_store="16"',
#     # "--cfg", 'target_has_atomic_load_store="32"',
#     # "--cfg", 'target_has_atomic_load_store="ptr"',
#     # # enable cas
#     # "--cfg", "target_has_atomic",
#     # "--cfg", 'target_has_atomic="8"',
#     # "--cfg", 'target_has_atomic="16"',
#     # "--cfg", 'target_has_atomic="32"',
#     # "--cfg", 'target_has_atomic="ptr"',
# ]

# [target.xtensa-esp32s3-none-elf]
# runner = "espflash flash --monitor"
# rustflags = [
#     "-C", "link-arg=-Tlinkall.x",
#     "-C", "link-arg=-Trom_functions.x",
# ]

# [target.xtensa-esp32s2-none-elf]
# runner = "espflash flash --monitor"
# rustflags = [
#     "-C", "link-arg=-Tlinkall.x",
#     "-C", "link-arg=-Trom_functions.x",

#     # Enable the atomic codegen option for Xtensa
#     "-C", "target-feature=+s32c1i",

#     # tell the core library have atomics even though it's not specified in the target definition
#     "--cfg", "target_has_atomic_load_store",
#     "--cfg", 'target_has_atomic_load_store="8"',
#     "--cfg", 'target_has_atomic_load_store="16"',
#     "--cfg", 'target_has_atomic_load_store="32"',
#     "--cfg", 'target_has_atomic_load_store="ptr"',
#     # Tell the `core` library that we have atomics, even though it's not
#     # specified in the target definition
#     "--cfg", 'target_has_atomic',
#     "--cfg", 'target_has_atomic="8"',
#     "--cfg", 'target_has_atomic="16"',
#     "--cfg", 'target_has_atomic="32"',
#     "--cfg", 'target_has_atomic="ptr"',
# ]

[unstable]
build-std = [ "core" , "alloc"]